server:
  port: 0
eureka:
  instance:
    hostname: localhost
    instace-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10086/eureka/
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/saga-account
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.tim.saga.demo.springcloud.account.entity
  config-location: classpath:mybatis/mybatis-config.xml