server:
  port: 10087
eureka:
  instance:
    hostname: localhost
    instace-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10086/eureka/
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/saga_order
    username: root
    password: 123456
  saga:
    repository:
      jdbc:
        url: jdbc:mysql://localhost:3306/saga
        user-name: root
        password: 123456
    recover:
      enable: true
      recover-duration: 300
logging:
  level:
    com.tim: DEBUG
mybatis:
  type-aliases-package: com.tim.saga.demo.springcloud.order.entity
  config-location: classpath:mybatis/mybatis-config.xml