spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/saga_account
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.tim.saga.demo.dubbo.account.entity
  config-location: classpath:mybatis/mybatis-config.xml
dubbo:
  scan:
    base-packages: com.tim.saga.demo.dubbo.account.service
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: account-service
    id: account-service
logging:
  level:
    org.apache.dubbo: DEBUG